This is makeindex, version 2.17 [TeX Live 2023] (kpathsea + Thai support).
Scanning style file ./memoria_tfg.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file memoria_tfg.acn....done (3 entries accepted, 0 rejected).
Sorting entries....done (4 comparisons).
Generating output file memoria_tfg.acr....done (6 lines written, 0 warnings).
Output written in memoria_tfg.acr.
Transcript written in memoria_tfg.alg.
